version: '3'

networks:
  wordpress-dev:
volumes:
  db:
  wordpress_core:

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_PORT: 80
    depends_on:
      - mysql
      - fpm_php
    volumes:
      - wordpress_core:/var/www/html

    networks:
      - wordpress-dev
      
  fpm_php:
    image: wordpress:5.7.2-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
        define( 'WP_DEBUG_LOG', true );
    volumes:
      - wordpress_core:/var/www/html
    networks:
      - wordpress-dev
    
  mysql:
    image: mysql:5.7.11
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress-dev
