version: '3'

networks:
  wordpress-dev:
volumes:
  db:

services:
  nginx:
    image: nginx:1.21.0
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: bcgov.test
      NGINX_PORT: 80
    depends_on:
      - mysql
    networks:
      - wordpress-dev
      
  wordpress:
    image: wordpress:5.7.2-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
  mysql:
    image: mysql:5.7.11
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wordpress-dev
